### ISSUE TITLE
can't farm magic essences, can you add an option ?

### ISSUE THREAD

**Issue by Ekinox49** [wildicedemon/SWAR-X#17]
Hello, 
I use your script, it seems to be very interesting, but i would like to farm magical essence, but the problem is that the game still waiting at the end window with the "OK" button. i think you made this script only for rune farm, can you make the modification for this ?

regards

**Comment by wildicedemon** [comment]
please download the latest version and take a screenshot and let me know what device you are using or the resolution. So that I can better assist you.

**Comment by Ekinox49** [comment]
My bad i said that without testing your script, i delete highlightOff and showstat function because my version of Ankulua pro don't understand this. But now it's working super fine, thank you very much for your work, if i improve your script with something interesting, you will be notified.
